---
title: "Maps"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r, echo=FALSE}

knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,viridis,
    tidyverse,
    cowplot,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}
```

# Data

## C16
### Map and trace Location
```{r}

C16Map_df <- read_csv(here("data","C16Map.csv")) %>% 
  clean_names() %>% 
  rename(y=x1,
         x=x2,
         z=x3) %>% 
  select(-x6)

C16Trace_df <- read_csv(here("data","C16Trace.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         dist=X4,
         mg_ca=X5,
         st_dev=X6)


C16Map_df %>%
  ggplot() +
  aes(x,
      y,
      col = log(mg_ca)) +
  geom_point(size = 0.2) +
  scale_color_viridis(option = "G",
                      begin = 0.01) +
  coord_fixed() +
  geom_path(data = C16Trace_df,
            aes(x = x, y = y),
            col = "red",
            linetype="dashed",
            size=0.7)



```

### Trace

```{r}
C16Trace_df %>% 
  ggplot()+
  aes(dist,mg_ca)+
  geom_line(show.legend = FALSE)+
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca ratio")
```


## C17

### Map
```{r}
C17MapB_df <- read_csv(here("data","C17MapB.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         mg_ca=X4,
         st_dev=X5) %>% 
    mutate(part="B")


C17MapB <- C17MapB_df %>%
  ggplot() +
  aes(x,
      y,
      col = log(mg_ca)) +
  geom_point(size = 0.5,show.legend = FALSE) +
  scale_color_viridis(option = "G",
                      begin = 0.01) +
  coord_fixed()

C17MapA_df <- read_csv(here("data","C17MapA.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         mg_ca=X4,
         st_dev=X5) %>% 
    mutate(part="A")


C17MapA <- C17MapA_df %>%
  ggplot() +
  aes(x,
      y,
      col = log(mg_ca)) +
  geom_point(size = 0.5,show.legend = FALSE) +
  scale_color_viridis(option = "G",
                      begin = 0.01) +
  coord_fixed()



C17MapRest_df <- read_csv(here("data","C17MapRest.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         mg_ca=X4,
         st_dev=X5) %>% 
  mutate(part="Rest")

C17MapRest <- C17MapRest_df %>%
  ggplot() +
  aes(x,
      y,
      col = log(mg_ca)) +
  geom_point(size = 1,show.legend = FALSE) +
  scale_color_viridis(option = "G",
                      begin = 0.01) +
  coord_fixed()

C17MapA+C17MapB
C17MapRest
```


```{r}
C17Map_df <- rbind(C17MapA_df,C17MapB_df,C17MapRest_df) %>% 
  mutate(x=if_else(part=="Rest",x-8500,if_else(part=="B",x-2200,x)),
         y=if_else(part=="Rest",y+5000,if_else(part=="B",y+2700,y))
         )

C17Map_df %>% 
ggplot() +
  aes(x,
      y,
      col = part) +
  geom_point(size = 0.5) +
  scale_color_viridis(option = "G",
                      begin = 0.1,
                      end = 0.9,
                      discrete = TRUE) +
   coord_fixed()
```

### Trace Location
```{r}

C17TraceB_df <- read_csv(here("data","C17TraceB.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         dist=X4,
         mg_ca=X5,
         st_dev=X6) %>% 
  mutate(x=x-2200, # to adjust for the changes in Part B above
         y=y+2700)

C17Map_df %>%
  ggplot() +
  aes(x,
      y,
      col = log(mg_ca)) +
  geom_point(size = 0.5) +
  scale_color_viridis(option = "G",
                      begin = 0.01) +
  coord_fixed()+
  geom_path(data = C17TraceB_df,
            aes(x = x, y = y),
            col = "red",
            linetype="dashed",
            size=0.7)





```

### Trace

```{r}
C17TraceB_df %>% 
  ggplot()+
  aes(dist,mg_ca)+
  geom_line()+
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca ratio")
```

