---
title: "Cellana test Mg/Ca and d18O"
output: pdf_document
---

```{r Libraries, echo=FALSE}

knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)
  
{
  pacman::p_load(
    here,ggx,
    janitor,
    tidyverse,
    cowplot,ShellChron,
    patchwork,
    RColorBrewer,
    dtw) 
  
  theme_set(theme_cowplot())
}
```

```{r Raw stable oxygen isotope data }
C16 <- tibble::tribble(
         ~specimen,    ~C,    ~O,
            "16-01",  -1.1,   1.2,
            "16-02",    -1,  0.98,
            "16-03", -0.94,  0.58,
            "16-04", -0.85, -0.16,
            "16-05", -0.87,  0.75,
            "16-06", -0.99,  0.28,
            "16-07", -1.08,  0.44,
            "16-08", -1.14,  0.52,
            "16-09", -0.91,  0.91,
            "16-10", -1.38,  1.45,
            "16-11",  -1.1,  1.68,
            "16-12", -0.74,  1.85,
            "16-13",  -0.5,  2.02,
            "16-14", -0.42,  1.97,
            "16-15", -0.42,  2.04,
            "16-16", -0.46,  2.05,
            "16-17", -0.51,  1.94,
            "16-18", -0.48,  2.15,
            "16-19", -0.51,  1.97,
            "16-20", -0.58,  1.76,
            "16-21", -0.67,  1.63,
            "16-22", -0.76,  1.67,
            "16-23", -1.23,  1.31,
            "16-24", -1.35,  1.48,
            "16-25", -1.33,  1.05,
            "16-26", -1.63,   0.9,
            "16-27", -1.76,  0.92,
            "16-28", -2.45,  0.58,
            "16-29", -1.85,  1.64,
            "16-30", -1.76,  1.95,
            "16-31", -1.58,  1.89,
            "16-32", -1.74,  1.26,
            "16-33", -1.52,  1.32,
            "16-34", -1.49,  0.83,
            "16-35", -2.08,  0.96,
            "16-36", -1.72,  1.17,
            "16-37",  -1.3,  1.39,
            "16-38", -1.32,  1.42,
            "16-39", -1.27,  1.42,
            "16-40", -1.32,  1.27,
            "16-41", -1.37,  0.68,
            "16-42", -1.69,  0.48,
            "16-43", -1.88,  0.45
         ) %>% 
  mutate(specimen="C16",
         sample_seq=1:43)

C17 <- tibble::tribble(
         ~specimen,    ~C,    ~O,
            "17-01",    -1,  1.15,
            "17-02",    -1,  1.05,
            "17-03",  -0.9,  0.58,
            "17-04", -0.73,  0.57,
            "17-09", -0.82,  0.63,
            "17-10", -1.27,  0.44,
            "17-12", -1.18,  0.49,
            "17-13", -0.95,  0.84,
            "17-14",  -1.1,  1.16,
            "17-15", -1.12,  1.06,
            "17-16", -1.48,  0.64,
            "17-17", -1.03,  1.67,
            "17-18",  -1.4,  1.09,
            "17-19", -0.59,  1.76,
            "17-20", -0.65,  1.95,
            "17-21", -0.57,  1.87,
            "17-22", -0.44,  2.19,
            "17-23", -0.41,   2.2,
            "17-24", -0.43,  1.87,
            "17-25", -0.33,     2,
            "17-26", -0.57,  1.95,
            "17-27", -0.62,  1.98,
            "17-28", -0.51,  1.78,
            "17-29", -0.62,  1.68,
            "17-30", -0.77,  1.23,
            "17-31", -1.16,  0.65,
            "17-32", -1.08,  0.47,
            "17-33", -1.33,  0.05,
            "17-34", -1.51,  0.03,
            "17-35", -1.66, -0.04,
            "17-36", -1.48,  -0.2,
            "17-37", -1.42, -0.26,
            "17-38",  -1.2,  0.48,
            "17-39", -1.06,  0.86,
            "17-40",  -0.8,   1.9,
            "17-41", -0.75,  1.73,
            "17-42",  -1.3,   1.1,
            "17-43", -1.77,  0.53,
            "17-44", -1.59,  0.49,
            "17-45", -2.38,  1.03,
            "17-46", -2.14,  1.37,
            "17-47", -1.92,  1.57,
            "17-49",  -2.1,  1.14,
            "17-50", -1.94,  1.14,
            "17-51", -2.11,     1,
            "17-52", -1.57,   1.3
) %>% 
  mutate(
    specimen="C17",
         sample_seq=c(1:4,9,10,12:47,49:52))

Cella <- full_join(C16,C17,by="sample_seq") %>% 
  select(sample_seq,everything(),-starts_with("specimen")) %>% 
  pivot_longer(cols = c(2:5),
               names_to = "element",
               values_to = "VPDB") %>% 
  separate(element, into=c("element","specimen")) %>% 
  mutate(specimen=if_else(specimen=="x","C16","C17"))

# write_csv(Cella,here("data","Cella.csv"))

```

# Plots

## Unchanged stable carbon and oxygen isotope data

```{r}
Cella %>% 
  ggplot()+
  aes(
    x=sample_seq,
    y=VPDB,
    col=element,
    linetype=specimen,
  )+
  geom_path()+
  geom_point() +
  xlab("Sample sequence")

```

\newpage

# Comparison of Oxygen Isotopes with Mg/Ca data

## C16 unaligned

```{r}

C16Trace_df <- read_csv(here("data","C16Trace.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         dist=X4,
         mg_ca=X5,
         st_dev=X6)

OmapC16 <- Cella %>% 
  filter(specimen=="C16",
         element=="O") %>% 
  ggplot()+
  aes(x=sample_seq,
      y=VPDB)+
  geom_path() +
    scale_y_reverse()+
  xlab("Sample sequence")+
  ylab("inverse VPDB")

  

x <- C16Trace_df %>%
  filter(dist<5.5) %>% 
  ggplot() +
  aes(x = dist,
      y = mg_ca) +
  xlim(0,5)+
  geom_path() +
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca Ratio")
  
OmapC16/MgCamapC16


```

## C17 unaligned

```{r}

C17TraceB_df <- read_csv(here("data","C17TraceB.csv"),col_names = FALSE) %>% 
  rename(y=X1,
         x=X2,
         z=X3,
         dist=X4,
         mg_ca=X5,
         st_dev=X6)

OmapC17 <- Cella %>% 
  filter(specimen=="C17",
         element=="O") %>% 
  ggplot()+
  aes(x=sample_seq,
      y=VPDB)+
  geom_path()+
    scale_y_reverse()+
  xlab("Sample sequence")+
  ylab("inverse VPDB")+
  ggtitle("",subtitle = "there are some gaps in this shell record")

MgCamapC17 <- C17TraceB_df %>%
  filter(dist<5.5) %>%
  ggplot() +
  aes(x = dist,
      y = mg_ca) +
  geom_path()+
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca Ratio")
  
OmapC17/MgCamapC17


```

\newpage

# Dynamic Time Warping and correlation graphs

## Aligning C16 records

### Warp data

```{r fig.height=4}

SeqC16_O <- C16 %>% 
  mutate(O=scale(O)) %>% 
  pull(O)
  
SeqC16_mg_ca <- C16Trace_df %>% 
    filter(dist<5.5) %>% 
    mutate(mg_ca=scale(mg_ca)) %>% 
  pull(mg_ca) 

alignment_C16 <- dtw(SeqC16_O*-1,SeqC16_mg_ca,
                 keep=TRUE,
                 step.pattern=symmetric2)
           
plot(alignment_C16,
     type = "twoway",
     offset = 3)
```

### Adjust data

```{r}

Al_C16_O <- C16 %>% 
  mutate(x=1:43,
         proxy="O") %>% 
  rename(value=O) %>% 
  select(x,value,proxy)
  
Al_C16_mg_ca <- C16Trace_df %>%
  filter(dist<5.5) %>%
  pull(mg_ca) %>%
  .[alignment_C16$index2] %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  rename(value=x) %>% 
  cbind(x=alignment_C16$index1) %>% 
    mutate(proxy="mg_ca")


C16_aligned <- rbind(Al_C16_O,Al_C16_mg_ca) %>% 
  group_by(x,proxy) %>%
  summarise(value=mean(value)) %>% #this unifies points that were given the same location
  ungroup() %>%
  mutate(value=round(value+0.000001*row_number(),5)) %>% #this adds some error to data points that are similar but far away from each other and prevents them to be grouped as one in the grouping step below
  group_by(proxy,value) %>% # this unifies extra points that were added to fill gaps in the record
  summarise(x=mean(x))


Al_C16_O_map <- C16_aligned %>%
  filter(proxy=="O") %>% 
ggplot()+
  aes(x=x,
      y=value)+
  geom_line()+
  scale_y_reverse()+
  xlab("arbitrary distance")+
  ylab("inverse VPDB")

Al_C16_mg_ca_map <- C16_aligned %>%
  filter(proxy=="mg_ca") %>% 
ggplot()+
  aes(x=x,
      y=value)+
  geom_line()+
  xlab("arbitrary distance")+
    ylab("Mg/Ca ratio")+
  ylim(0.2,0.4)



Al_C16_O_map/Al_C16_mg_ca_map


```

\newpage

## Aligning C17 records

### Warp data

```{r}

SeqC17_O <- C17 %>% 
  mutate(O=scale(O)) %>% 
  pull(O)
  
SeqC17_mg_ca <- C17TraceB_df %>% 
    filter(dist<5.2) %>% 
    mutate(mg_ca=scale(mg_ca)) %>% 
  pull(mg_ca) 

alignment_C17 <- dtw(SeqC17_O*-1,SeqC17_mg_ca,
                 keep=TRUE,
                 step.pattern=symmetric2)
           
plot(alignment_C17,
     type = "twoway",
     offset = 3)
```

### Adjust data

```{r}

Al_C17_O <- C17 %>% 
  mutate(x=1:46,
         proxy="O") %>% 
  rename(value=O) %>% 
  select(x,value,proxy)
  
Al_C17_mg_ca <- C17TraceB_df %>%
  filter(dist<5.2) %>%
  pull(mg_ca) %>%
  .[alignment_C17$index2] %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  rename(value=x) %>% 
  cbind(x=alignment_C17$index1) %>% 
    mutate(proxy="mg_ca")


C17_aligned <- rbind(Al_C17_O,Al_C17_mg_ca) %>% 
  group_by(x,proxy) %>%
  summarise(value=mean(value)) %>% #this unifies points that were given the same location
  ungroup() %>%
  mutate(value=round(value+0.000001*row_number(),5)) %>% #this adds some error to data points that are similar but far away from each other and prevents them to be grouped as one in the grouping step below
  group_by(proxy,value) %>% # this unifies extra points that were added to fill gaps in the record
  summarise(x=mean(x))


Al_C17_O_map <- C17_aligned %>%
  filter(proxy=="O") %>% 
ggplot()+
  aes(x=x,
      y=value)+
    scale_y_reverse()+
  geom_line()+
  xlab("arbitrary distance")+
  ylab("inverse VPDB")

Al_C17_mg_ca_map <- C17_aligned %>%
  filter(proxy=="mg_ca") %>% 
ggplot()+
  aes(x=x,
      y=value)+
  geom_line()+
  xlab("arbitrary distance")+
    ylab("Mg/Ca ratio")+
  ylim(0.2,0.55)



Al_C17_O_map/Al_C17_mg_ca_map

```

# Correlation Graphs

```{r}

df_C16 <- C16_aligned %>%
  pivot_wider(names_from = "proxy",
              values_from = "value") %>% 
  select(O,mg_ca)

LM_C16 <- lm(O ~ mg_ca,
         data=df_C16,
         )
R2_C16 <- round(summary(LM_C16)[[8]],2)


df_C17 <- C17_aligned %>%
  pivot_wider(names_from = "proxy",
              values_from = "value") %>% 
  select(O,mg_ca)

LM_C17 <- lm(O ~ mg_ca,
         data=df_C17,
         )
R2_C17 <- round(summary(LM_C17)[[8]],2)

# C16_aligned %>%
#   mutate(specimen = "C16") %>%
#   rbind(C17_aligned %>% mutate(specimen = "C17")) %>%
#   pivot_wider(names_from = "proxy",
#               values_from = "value") %>%
#   ggplot() +
#   aes(x = O,
#       y = mg_ca,
#       col = specimen) +
#   geom_point() +
#   xlim(-0.5, 2.5) +
#   ylim(0.2, 0.5) +
#   geom_smooth(method = "lm", se = FALSE) +
#   annotate("text",
#            x = 0,
#            y = 0.3,
#            label = paste("R²=", R2_C16)) +
#   annotate("text",
#            x = 1.1,
#            y = 0.45,
#            label = paste("R²=", R2_C17)) +
#   ylab("Mg/Ca Ratio") +
#   xlab("d18O VPDB")

C16_aligned %>%
  pivot_wider(names_from = "proxy",
              values_from = "value") %>%
  ggplot() +
  aes(x = O,
      y = mg_ca) +
  geom_point() +
  xlim(-0.5, 2.5) +
  ylim(0.2, 0.5) +
  geom_smooth(method = "lm",
              se = FALSE,
              col="black",
              linetype="dashed",
              size=0.5) +
  ylab("Mg/Ca Ratio") +
  xlab("d18O VPDB")+
  ggtitle("Correlation graph for C16 d18O and Mg/Ca",
          subtitle = paste("R²=", R2_C16))

C17_aligned %>%
  pivot_wider(names_from = "proxy",
              values_from = "value") %>%
  ggplot() +
  aes(x = O,
      y = mg_ca) +
  geom_point() +
  xlim(-0.5, 2.5) +
  ylim(0.2, 0.5) +
  geom_smooth(method = "lm",
              se = FALSE,
              col="black",
              linetype="dashed",
              size=0.5) +
  ylab("Mg/Ca Ratio") +
  xlab("d18O VPDB")+
  ggtitle("Correlation graph for C17 d18O and Mg/Ca",
          subtitle = paste("R²=", R2_C17))
```
