---
output: pdf_document
---

```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)


{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,scales,
    patchwork,ShellChron,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}


```


```{r}

Cella <- read.csv(here("data","Cella.csv"))


SST <- read.csv(here("data", "SST_Wynard.csv")) %>%
  clean_names() %>%
  separate(day, into = c("day", "month"), extra = "drop") %>%
  pivot_longer(names_to = "year",
               values_to = "SST",
               cols = starts_with("x")) %>%
  unite(c("year", "month", "day"), col = "date", sep = "/") %>%
  mutate(date = gsub("x", "", date),
         date = as.Date(date)) %>% 
  arrange(date)



C16Trace_df <- read.csv(here("data","C16.csv")) %>% 
                filter(sample_mode=="trace")



# 
# ,col_names = FALSE) %>% 
#   rename(y=X1,
#          x=X2,
#          z=X3,
#          dist=X4,
#          mg_ca=X5,
#          st_dev=X6)

C17Trace_df <- read.csv(here("data","C17.csv")) %>% 
                filter(sample_mode=="trace")
  
  
  # read_csv(here("data","C17TraceB.csv"),col_names = FALSE) %>% 
  # rename(y=X1,
  #        x=X2,
  #        z=X3,
  #        dist=X4,
  #        mg_ca=X5,
  #        st_dev=X6)

```

```{r Plot SST+C16, fig.height=9, fig.width=8}



SST_plot <- SST %>% 
  filter(date>"2014-01-01",
         date<"2017-06-02") %>% 
  ggplot()+
  aes(x=date,y=SST) +
  geom_line()+
  ylab("SST ºC")+
  geom_vline(xintercept = as.numeric(as.Date("2014-02-25")), linetype=2)+
  geom_vline(xintercept = as.numeric(as.Date("2015-02-25")), linetype=2)+
  geom_vline(xintercept = as.numeric(as.Date("2016-02-10")), linetype=2)+
  geom_vline(xintercept = as.numeric(as.Date("2017-03-20")), linetype=2)

# 
#   O18_SST_plot <-
#   SST %>% 
#     d18O_model(d18Ow=.6) %>% 
#   filter(date>"2015-06-02",
#          date<"2017-06-02") %>% 
#   ggplot()+
#   aes(x=date,y=SST) +
#   geom_line()+
#   geom_vline(xintercept = as.numeric(as.Date("2017-03-20")), linetype=2)+
#   geom_vline(xintercept = as.numeric(as.Date("2016-02-10")), linetype=2)+
#   ylim(-0.5,2.5)

C16_O_plot <- Cella %>% 
  filter(element=="O",
         specimen=="C16") %>%
  na.omit() %>% 
  ggplot()+
  aes(x=sample_seq,y=VPDB)+
  geom_line()+
  geom_vline(xintercept = 43, linetype=2)+
  geom_vline(xintercept = 34, linetype=2)+
  geom_vline(xintercept = 28, linetype=2)+
  geom_vline(xintercept = 4, linetype=2)+
  ylim(-0.5,2.5)+
  ylab(expression("δ" ^ "18" * "O [VPDB]"))+
  xlab("sample number")+
  scale_x_reverse()+
  scale_y_reverse()


C16_Mg_Ca_plot <-
  C16Trace_df %>%
  # filter(dist<5.5) %>% 
  ggplot() +
  aes(x = dist,
      y = mg_ca) +
  # xlim(0,5)+
  geom_path() +
  scale_x_reverse()+
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca ratio")+
  geom_vline(xintercept = 0.3, linetype=2)+
  geom_vline(xintercept = 3.5, linetype=2)+
  geom_vline(xintercept = 8.9, linetype=2)+
  geom_vline(xintercept = 6, linetype=2)+
  geom_vline(xintercept = 4.4, linetype=2)+
  annotate("rect", xmin = 0, xmax = 6.05, ymin = 0.25, ymax = 0.47,
  alpha = .2)+
  annotate("text",x=1.3,y=0.49,label="extent of d18O record", alpha=.6)

SST_plot/C16_O_plot/C16_Mg_Ca_plot+plot_annotation(title = "C16")

```

\newpage
```{r Plot SST+C17, fig.height=9, fig.width=8}
C17_O_plot <- Cella %>% 
  filter(element=="O",
         specimen=="C17") %>% 
  ggplot()+
  aes(x=sample_seq,y=VPDB)+
  geom_line()+
  geom_vline(xintercept = 10, linetype=2)+
  geom_vline(xintercept = 37, linetype=2)+
  geom_vline(xintercept = 44, linetype=2)+
  geom_vline(xintercept = 51, linetype=2)+
  ylim(-0.5,2.5)+
  ylab(expression("δ" ^ "18" * "O [VPDB]"))+
  xlab("sample number")+
  scale_x_reverse()+
  scale_y_reverse()


C17_Mg_Ca_plot <-
  C17Trace_df %>%
  # filter(dist<5.5) %>% 
  ggplot() +
  aes(x = dist,
      y = mg_ca) +
  # xlim(0,5)+
  geom_path() +
  scale_x_reverse()+
  xlab("Distance to Edge [mm]")+
  ylab("Mg/Ca ratio")+
  geom_vline(xintercept = 0.8, linetype=2)+
  geom_vline(xintercept = 3.5, linetype=2)+
  geom_vline(xintercept = 8.6, linetype=2)+
  geom_vline(xintercept = 5.4, linetype=2)+
  geom_vline(xintercept = 4.7, linetype=2)+
  annotate("rect", xmin = 0, xmax = 5.6, ymin = 0.25, ymax = 0.61,
  alpha = .2)+
  annotate("text",x=1.8,y=0.65,label="extent of d18O record", alpha=.6)



SST_plot/C17_O_plot/C17_Mg_Ca_plot+plot_annotation(title = "C17")

```
