---
title: "Chlo-alpha plot"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,lubridate,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}
```

# Data

```{r}

Chl <- read_csv("data/chl.csv", col_types = cols(time = col_character()),skip = 6) %>% 
  mutate(time=lubridate::as_date(time),
         time=round_date(time,unit="month"),
         month=as_factor(month(time)),
         year= as_factor(year(time)))


```



# Plot
```{r}

Chl %>%
  group_by(month) %>%
  summarize(avg_chl = mean(chl, na.rm = TRUE),
            sd_chl = sd(chl, na.rm = TRUE)) %>% 
ggplot()+
  aes(x = month, y = avg_chl, group=1) +
    # geom_point(data=Chl,aes(x=month,y=chl,group=year),col="darkgreen",alpha=0.3) +
  geom_path(col="darkgreen",linewidth=1) +
  geom_ribbon(aes(ymin = avg_chl - sd_chl, ymax = avg_chl + sd_chl),
              alpha = 0.3,fill="darkgreen") +
  xlab("Month") +
  ylab(expression("Average mass concentration of chlorophyll-a (mg/m"^3*")")) +
  ylim(0,3)+
# scale_y_log10(breaks = c(0.1, 0.5,1,5, 10, 100),
#                 labels = c("0.1", "0.5","1", "5", "10", "100"),limits = c(0.1, 10))+
  ggtitle("Monthly Changes in Chlorophyll-a", subtitle= "Period of 1997 - 2023")+
  theme_cowplot(20)

# ggsave(here("figures","Chl-a.png"))
```


